os:
  - linux
  - osx

matrix:
  - os: linux
    env: EJS_RUNLOOP_IMPL=noop

language: c++

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5814034db461e2eff65d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sh ./ci/setup-pkg-$TRAVIS_OS_NAME.sh

install:
  - export PATH=$PATH:/usr/local/share/npm/bin
  - sh ./ci/install-node-$TRAVIS_OS_NAME.sh
  - sh ./ci/install-llvm-$TRAVIS_OS_NAME.sh

before_script:
  - export LLVM_SUFFIX=
  - export PATH=$PATH:`npm prefix -g`/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - export NODE_PATH=`make --no-print-directory -C test node-path`
  - make

script:
  - export LLVM_SUFFIX=
  - export PATH=$PATH:`npm prefix -g`/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - export NODE_PATH=`make -C test node-path`
  - touch test/expected/*.expected-out
  - make -C test check-stage0
  - make -C test check-stage1
  - make -C test check-stage2
