os:
  - linux
  - osx

language: c++

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5814034db461e2eff65d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sh ./ci/setup-pkg-$TRAVIS_OS_NAME.sh

install:
  - export PATH=$PATH:/usr/local/share/npm/bin
  - sh ./ci/install-node-$TRAVIS_OS_NAME.sh
  - sh ./ci/install-llvm-$TRAVIS_OS_NAME.sh

before_script:
  - export LLVM_SUFFIX=
  - export PATH=$PATH:/usr/local/share/npm/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - export NODE_PATH=`make -C test node-path`
  - make

script:
  - export LLVM_SUFFIX=
  - export PATH=$PATH:/usr/local/share/npm/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/llvm
  - export NODE_PATH=`make -C test node-path`
  - touch test/expected/*.expected-out
  - EJS_STAGE=0 EJS_DRIVER="`pwd`/ejs" make -C test check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
  - make -C test clean
  - EJS_STAGE=1 EJS_DRIVER="`pwd`/ejs.exe.stage1" make -C test check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
  - make -C test clean
  - EJS_STAGE=2 EJS_DRIVER="`pwd`/ejs.exe.stage2" make -C test check
  - if test -f test/.failures -o -f test/.xsuccess; then exit -1; fi
